title: the comforts of home
email: rlb9fd@virginia.edu
description: >- # this means to ignore newlines until "baseurl:"
  An online interactive multimedia work.
baseurl: "/comforts-of-home" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  thely

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock